### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by heitortsergent** [npmawesome/npmawesome.com#14]
Getting an error message when trying to access the website: "Error establishing a database connection"

![image](https://cloud.githubusercontent.com/assets/446316/6417583/e6bcc376-be73-11e4-94c0-69a31b4cbc8e.png)

**Comment by alexgorbatchev** [comment]
Thanks for heads up! Fixed.

**Comment by heitortsergent** [comment]
:+1: :D
