### ISSUE TITLE
webdriver.js page has wrong description

### ISSUE THREAD

**Issue by fent** [npmawesome/npmawesome.com#5]
http://npmawesome.com/posts/2014-02-25-webdriverjs/

> webdriver.js is a module by Camilo Tapia to render node.js error stack in a much more digestable way. This seems like it might a good module to add to your infrastracture if you, like me, constantly having to weed through the ugly stack messages to find relavant lines.

**Comment by alexgorbatchev** [comment]
Fixed, thanks for noticing this!
